package org.apache.plc4x.java.base.next.optimizer;

import org.apache.commons.lang3.tuple.Pair;

/**
 * Inverse Transformation Interface which is generated by a @{@link MergeRule}.
 *
 * @param <RES> Response Type
 */
public interface InverseTransformation<RES extends FieldResponse> {

    Pair<RES, RES> apply(RES response);

}
